
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 24;
  public static final int IDENT = 26;
  public static final int ELSE = 5;
  public static final int PLUS = 22;
  public static final int INT = 2;
  public static final int SEMI = 15;
  public static final int END = 14;
  public static final int RETURN = 8;
  public static final int TRUE = 9;
  public static final int IF = 4;
  public static final int BEGIN = 13;
  public static final int STRING = 27;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int DEC = 21;
  public static final int MINUS = 23;
  public static final int FALSE = 10;
  public static final int DOT = 17;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int NEW = 7;
  public static final int GTEQ = 19;
  public static final int INTEGER = 25;
  public static final int RPAR = 12;
  public static final int FOR = 6;
  public static final int NEQ = 20;
  public static final int VOID = 3;
  public static final int LPAR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "VOID",
  "IF",
  "ELSE",
  "FOR",
  "NEW",
  "RETURN",
  "TRUE",
  "FALSE",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "SEMI",
  "COMMA",
  "DOT",
  "ASSIGN",
  "GTEQ",
  "NEQ",
  "DEC",
  "PLUS",
  "MINUS",
  "MOD",
  "INTEGER",
  "IDENT",
  "STRING"
  };
}

